server:
  port: 8080
spring:
  application:
    name: currency
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/currency
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

myapp:
  properties:
    token: "fca_live_lQrLEGyHXAK0mFS5X0h5qNc2myUxh3KR8DtQF65B"
    baseUrl: "https://api.freecurrencyapi.com/v1/latest?apikey=fca_live_lQrLEGyHXAK0mFS5X0h5qNc2myUxh3KR8DtQF65B"
  

